FROM node:16-alpine

# Copy dependency files
COPY package*.json ./

# Install dependencies
RUN npm ci \
  && rm package*.json

# Setup chromium for tests. Will be put back if needed
# RUN apk add --no-cache chromium
# ENV CHROME_BIN=/usr/bin/chromium-browser
